trigger:
- master
- release/*
- beta/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm run test'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test'

- task: Npm@1
  displayName: 'npm run tsc'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run tsc'
