trigger:
- master
- beta
- beta/*

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: Npm@1
#   displayName: 'npm install'
#   inputs:
#     verbose: false

# - task: Npm@1
#   displayName: 'npm run test'
#   inputs:
#     command: custom
#     verbose: false
#     customCommand: 'run test'

# - task: Npm@1
#   displayName: 'npm run tsc'
#   inputs:
#     command: custom
#     verbose: false
#     customCommand: 'run tsc'

- task: Npm@1
  displayName: 'npm run semantic-release'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run semantic-release'
